name: Main kittygram workflow

on:
  push:
    branches:
      - master

jobs:
  pull_images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Copy docker-compose.yml via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "docker-compose.production.yml"
        target: "kittygram"

    - name: Pull Docker images
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          set -e
          cd kittygram
          echo "Pulling images..."
          sudo docker compose -f docker-compose.production.yml pull || echo "Failed to pull images"

  restart_services:
    runs-on: ubuntu-latest
    needs: pull_images
    steps:
    - name: Stop old services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          set -e
          cd kittygram
          echo "Stopping old services..."
          sudo docker compose -f docker-compose.production.yml down || echo "Failed to stop services"

    - name: Start new services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          set -e
          cd kittygram
          echo "Starting new services..."
          sudo docker compose -f docker-compose.production.yml up -d || echo "Failed to start services"

  run_migrations:
    runs-on: ubuntu-latest
    needs: restart_services
    steps:
    - name: Run migrations
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          set -e
          cd kittygram
          echo "Running migrations..."
          sudo docker compose -f docker-compose.production.yml exec backend python manage.py migrate || echo "Migration failed"

    - name: Collect static files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          set -e
          cd kittygram
          echo "Collecting static files..."
          sudo docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic --noinput || echo "Collectstatic failed"

  send_message:
    runs-on: ubuntu-latest
    needs: run_migrations
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Деплой выполнен!
          Пользователь: ${{ github.actor }}
          Сообщение коммита: ${{ github.event.commits[0].message }}
